[package]
edition = "2021"
name = "blockchain"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.23"
serde = {version = "1.0.147", features = ["derive"]}
serde_json = "1.0.87"
sha2 = "0.10.6"
